In [54]:
%matplotlib inline
from matplotlib import style
style.use('fivethirtyeight')
import matplotlib.pyplot as plt

In [55]:
import numpy as np
import pandas as pd

In [56]:
import datetime as dt

# Reflect Tables into SQLAlchemy ORM

In [57]:
# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func

In [58]:
engine = create_engine("sqlite:///Resources/hawaii.sqlite")

In [59]:
# reflect an existing database into a new model
Base = automap_base()
# reflect the tables
Base.prepare(engine, reflect=True)

In [60]:
# We can view all of the classes that automap found
Base.classes.keys()

['measurement', 'station']

In [61]:
# Save references to each table
Measurement = Base.classes.measurement
Station = Base.classes.station

In [62]:
# Create our session (link) from Python to the DB
session = Session(engine)

# Exploratory Climate Analysis

In [63]:
# Design a query to retrieve the last 12 months of precipitation data and plot the results

# Calculate the date 1 year ago from the last data point in the database

# Perform a query to retrieve the data and precipitation scores

# Save the query 

# Sort the dataframe by date

# Use Pandas Plotting with Matplotlib to plot the data

In [64]:
end_date = session.query(Measurement.date).order_by(Measurement.date.desc()).first()
print(end_date)

('2017-08-23',)

In [65]:
query_date = dt.date(2017, 8, 23) - dt.timedelta(days=365)
print(query_date)

2016-08-23

In [66]:
sel = [Measurement.date, Measurement.prcp]
date_range = session.query(*sel).\
    filter(Measurement.date >= query_date).\
    group_by(Measurement.date).\
    order_by(Measurement.date).all()
date_range

[('2016-08-23', 0.7),
 ('2016-08-24', 1.45),
 ('2016-08-25', 0.11),
 ('2016-08-26', 0.01),
 ('2016-08-27', None),
 ('2016-08-28', 2.07),
 ('2016-08-29', 0.9),
 ('2016-08-30', 0.05),
 ('2016-08-31', 2.46),
 ('2016-09-01', 0.01),
 ('2016-09-02', 0.03),
 ('2016-09-03', 1.0),
 ('2016-09-04', 0.44),
 ('2016-09-05', 0.18),
 ('2016-09-06', 1.0),
 ('2016-09-07', 1.35),
 ('2016-09-08', 0.15),
 ('2016-09-09', 0.35),
 ('2016-09-10', 1.16),
 ('2016-09-11', 0.6),
 ('2016-09-12', 1.04),
 ('2016-09-13', 1.2),
 ('2016-09-14', 6.7),
 ('2016-09-15', 3.35),
 ('2016-09-16', 0.61),
 ('2016-09-17', 0.23),
 ('2016-09-18', 0.42),
 ('2016-09-19', 0.25),
 ('2016-09-20', 0.43),
 ('2016-09-21', 1.02),
 ('2016-09-22', 0.75),
 ('2016-09-23', 0.33),
 ('2016-09-24', 0.27),
 ('2016-09-25', 0.04),
 ('2016-09-26', 1.02),
 ('2016-09-27', 1.0),
 ('2016-09-28', 0.05),
 ('2016-09-29', 1.49),
 ('2016-09-30', 0.38),
 ('2016-10-01', 1.02),
 ('2016-10-02', 0.61),
 ('2016-10-03', 0.46),
 ('2016-10-04', 3.46),
 ('2016-10-05', 0.81),
 ('2016-10-06', 0.04),
 ('2016-10-07', 0.01),
 ('2016-10-08', 0.04),
 ('2016-10-09', 0.0),
 ('2016-10-10', 0.0),
 ('2016-10-11', 0.35),
 ('2016-10-12', 0.02),
 ('2016-10-13', 0.06),
 ('2016-10-14', 0.0),
 ('2016-10-15', 0.33),
 ('2016-10-16', 0.0),
 ('2016-10-17', 0.38),
 ('2016-10-18', 0.48),
 ('2016-10-19', 0.0),
 ('2016-10-20', 1.0),
 ('2016-10-21', 0.09),
 ('2016-10-22', 1.37),
 ('2016-10-23', 0.24),
 ('2016-10-24', 0.7),
 ('2016-10-25', 0.4),
 ('2016-10-26', 0.0),
 ('2016-10-27', 1.25),
 ('2016-10-28', 0.37),
 ('2016-10-29', 0.25),
 ('2016-10-30', 0.95),
 ('2016-10-31', 1.35),
 ('2016-11-01', 0.09),
 ('2016-11-02', 0.04),
 ('2016-11-03', 0.02),
 ('2016-11-04', 0.06),
 ('2016-11-05', 0.38),
 ('2016-11-06', 0.05),
 ('2016-11-07', 0.05),
 ('2016-11-08', 0.53),
 ('2016-11-09', 0.04),
 ('2016-11-10', 0.01),
 ('2016-11-11', 0.0),
 ('2016-11-12', 0.0),
 ('2016-11-13', 0.0),
 ('2016-11-14', 0.02),
 ('2016-11-15', 0.05),
 ('2016-11-16', 0.91),
 ('2016-11-17', 0.02),
 ('2016-11-18', 0.0),
 ('2016-11-19', 0.11),
 ('2016-11-20', None),
 ('2016-11-21', 2.87),
 ('2016-11-22', 2.11),
 ('2016-11-23', 0.22),
 ('2016-11-24', 0.72),
 ('2016-11-25', 1.03),
 ('2016-11-26', 0.3),
 ('2016-11-27', 0.29),
 ('2016-11-28', 0.69),
 ('2016-11-29', 0.2),
 ('2016-11-30', 0.79),
 ('2016-12-01', 0.72),
 ('2016-12-02', 1.27),
 ('2016-12-03', 1.62),
 ('2016-12-04', 0.31),
 ('2016-12-05', 1.6),
 ('2016-12-06', 0.0),
 ('2016-12-07', 0.02),
 ('2016-12-08', 0.03),
 ('2016-12-09', 0.42),
 ('2016-12-10', 0.04),
 ('2016-12-11', 0.13),
 ('2016-12-12', 0.01),
 ('2016-12-13', 0.09),
 ('2016-12-14', 0.33),
 ('2016-12-15', 0.03),
 ('2016-12-16', 0.0),
 ('2016-12-17', 0.07),
 ('2016-12-18', None),
 ('2016-12-19', 0.15),
 ('2016-12-20', 0.0),
 ('2016-12-21', 0.55),
 ('2016-12-22', 1.24),
 ('2016-12-23', 0.83),
 ('2016-12-24', 1.08),
 ('2016-12-25', 0.38),
 ('2016-12-26', 1.48),
 ('2016-12-27', 0.14),
 ('2016-12-28', 0.14),
 ('2016-12-29', 1.03),
 ('2016-12-30', 2.37),
 ('2016-12-31', 0.9),
 ('2017-01-01', 0.03),
 ('2017-01-02', 0.0),
 ('2017-01-03', 0.0),
 ('2017-01-04', 0.0),
 ('2017-01-05', 0.47),
 ('2017-01-06', 0.1),
 ('2017-01-07', 0.0),
 ('2017-01-08', 0.03),
 ('2017-01-09', 0.0),
 ('2017-01-10', 0.0),
 ('2017-01-11', 0.0),
 ('2017-01-12', 0.0),
 ('2017-01-13', 0.0),
 ('2017-01-14', 0.0),
 ('2017-01-15', 0.01),
 ('2017-01-16', 0.0),
 ('2017-01-17', 0.0),
 ('2017-01-18', 0.07),
 ('2017-01-19', 0.0),
 ('2017-01-20', 0.0),
 ('2017-01-21', 0.08),
 ('2017-01-22', 0.72),
 ('2017-01-23', 0.85),
 ('2017-01-24', 1.85),
 ('2017-01-25', 2.64),
 ('2017-01-26', 0.1),
 ('2017-01-27', 0.03),
 ('2017-01-28', 0.0),
 ('2017-01-29', 0.55),
 ('2017-01-30', 0.0),
 ('2017-01-31', 0.0),
 ('2017-02-01', 0.0),
 ('2017-02-02', 0.0),
 ('2017-02-03', 0.0),
 ('2017-02-04', None),
 ('2017-02-05', 0.0),
 ('2017-02-06', 0.0),
 ('2017-02-07', 1.79),
 ('2017-02-08', 0.0),
 ('2017-02-09', 0.0),
 ('2017-02-10', 0.0),
 ('2017-02-11', 0.73),
 ('2017-02-12', 1.83),
 ('2017-02-13', 0.0),
 ('2017-02-14', 0.01),
 ('2017-02-15', 0.07),
 ('2017-02-16', 0.13),
 ('2017-02-17', 0.13),
 ('2017-02-18', None),
 ('2017-02-19', 0.1),
 ('2017-02-20', 0.0),
 ('2017-02-21', 0.07),
 ('2017-02-22', 0.32),
 ('2017-02-23', 0.0),
 ('2017-02-24', 0.0),
 ('2017-02-25', 0.12),
 ('2017-02-26', 0.0),
 ('2017-02-27', 0.0),
 ('2017-02-28', 0.58),
 ('2017-03-01', 2.0),
 ('2017-03-02', 0.58),
 ('2017-03-03', 0.56),
 ('2017-03-04', 0.0),
 ('2017-03-05', 0.35),
 ('2017-03-06', 0.0),
 ('2017-03-07', 0.0),
 ('2017-03-08', 0.0),
 ('2017-03-09', 0.01),
 ('2017-03-10', 0.0),
 ('2017-03-11', 0.0),
 ('2017-03-12', 0.0),
 ('2017-03-13', None),
 ('2017-03-14', 0.0),
 ('2017-03-15', 0.0),
 ('2017-03-16', 0.0),
 ('2017-03-17', 0.12),
 ('2017-03-18', None),
 ('2017-03-19', 0.0),
 ('2017-03-20', 0.0),
 ('2017-03-21', 0.0),
 ('2017-03-22', 0.0),
 ('2017-03-23', 0.03),
 ('2017-03-24', 0.17),
 ('2017-03-25', 0.48),
 ('2017-03-26', 0.0),
 ('2017-03-27', 0.0),
 ('2017-03-28', 0.68),
 ('2017-03-29', 0.07),
 ('2017-03-30', 0.04),
 ('2017-03-31', None),
 ('2017-04-01', 0.2),
 ('2017-04-02', 0.0),
 ('2017-04-03', 0.23),
 ('2017-04-04', 0.02),
 ('2017-04-05', 0.45),
 ('2017-04-06', 0.0),
 ('2017-04-07', 0.0),
 ('2017-04-08', None),
 ('2017-04-09', 0.0),
 ('2017-04-10', 0.0),
 ('2017-04-11', 0.25),
 ('2017-04-12', 0.65),
 ('2017-04-13', 0.23),
 ('2017-04-14', 2.82),
 ('2017-04-15', 0.9),
 ('2017-04-16', 0.11),
 ('2017-04-17', 1.3),
 ('2017-04-18', 0.98),
 ('2017-04-19', 0.14),
 ('2017-04-20', 0.0),
 ('2017-04-21', 1.84),
 ('2017-04-22', 1.35),
 ('2017-04-23', 0.35),
 ('2017-04-24', 0.05),
 ('2017-04-25', 0.0),
 ('2017-04-26', 0.22),
 ('2017-04-27', 0.11),
 ('2017-04-28', 0.79),
 ('2017-04-29', 0.0),
 ('2017-04-30', 0.8),
 ('2017-05-01', 0.25),
 ('2017-05-02', 0.0),
 ('2017-05-03', 0.01),
 ('2017-05-04', None),
 ('2017-05-05', 0.1),
 ('2017-05-06', 0.0),
 ('2017-05-07', 0.03),
 ('2017-05-08', 1.11),
 ('2017-05-09', 0.23),
 ('2017-05-10', 0.55),
 ('2017-05-11', 0.44),
 ('2017-05-12', 0.1),
 ('2017-05-13', 0.1),
 ('2017-05-14', 1.0),
 ('2017-05-15', 0.6),
 ('2017-05-16', 0.3),
 ('2017-05-17', 0.06),
 ('2017-05-18', 0.0),
 ('2017-05-19', 0.01),
 ('2017-05-20', None),
 ('2017-05-21', 0.0),
 ('2017-05-22', 0.3),
 ('2017-05-23', 0.44),
 ('2017-05-24', 2.17),
 ('2017-05-25', 0.88),
 ('2017-05-26', 0.0),
 ('2017-05-27', 0.5),
 ('2017-05-28', 0.0),
 ('2017-05-29', 0.4),
 ('2017-05-30', None),
 ('2017-05-31', 0.25),
 ('2017-06-01', 0.01),
 ('2017-06-02', 0.09),
 ('2017-06-03', None),
 ('2017-06-04', 0.82),
 ('2017-06-05', 0.01),
 ('2017-06-06', 0.0),
 ('2017-06-07', 0.01),
 ('2017-06-08', 0.0),
 ('2017-06-09', 0.02),
 ('2017-06-10', None),
 ('2017-06-11', 0.7),
 ('2017-06-12', 0.81),
 ('2017-06-13', 0.65),
 ('2017-06-14', 0.81),
 ('2017-06-15', 1.69),
 ('2017-06-16', 0.1),
 ('2017-06-17', 0.1),
 ('2017-06-18', 0.7),
 ('2017-06-19', 0.4),
 ('2017-06-20', 0.31),
 ('2017-06-21', 0.3),
 ('2017-06-22', 0.28),
 ('2017-06-23', 0.5),
 ('2017-06-24', 0.22),
 ('2017-06-25', 0.5),
 ('2017-06-26', 0.02),
 ('2017-06-27', 0.1),
 ('2017-06-28', 0.02),
 ('2017-06-29', 0.04),
 ('2017-06-30', 0.2),
 ('2017-07-01', 0.1),
 ('2017-07-02', 0.5),
 ('2017-07-03', 0.4),
 ('2017-07-04', 0.0),
 ('2017-07-05', 0.0),
 ('2017-07-06', 0.02),
 ('2017-07-07', 0.3),
 ('2017-07-08', 0.02),
 ('2017-07-09', 0.0),
 ('2017-07-10', 0.02),
 ('2017-07-11', 0.0),
 ('2017-07-12', 0.05),
 ('2017-07-13', 0.68),
 ('2017-07-14', 0.68),
 ('2017-07-15', 0.1),
 ('2017-07-16', 0.5),
 ('2017-07-17', 0.39),
 ('2017-07-18', 2.4),
 ('2017-07-19', 0.27),
 ('2017-07-20', 0.7),
 ('2017-07-21', 0.1),
 ('2017-07-22', 4.0),
 ('2017-07-23', 0.8),
 ('2017-07-24', 0.84),
 ('2017-07-25', 0.3),
 ('2017-07-26', 0.3),
 ('2017-07-27', 0.0),
 ('2017-07-28', 0.4),
 ('2017-07-29', 0.3),
 ('2017-07-30', 0.3),
 ('2017-07-31', 0.0),
 ('2017-08-01', None),
 ('2017-08-02', 0.25),
 ('2017-08-03', 0.06),
 ('2017-08-04', 0.0),
 ('2017-08-05', None),
 ('2017-08-06', None),
 ('2017-08-07', 0.05),
 ('2017-08-08', 0.34),
 ('2017-08-09', 0.15),
 ('2017-08-10', 0.07),
 ('2017-08-11', None),
 ('2017-08-12', 0.14),
 ('2017-08-13', None),
 ('2017-08-14', 0.22),
 ('2017-08-15', 0.42),
 ('2017-08-16', 0.42),
 ('2017-08-17', 0.13),
 ('2017-08-18', None),
 ('2017-08-19', 0.09),
 ('2017-08-20', None),
 ('2017-08-21', 0.56),
 ('2017-08-22', 0.5),
 ('2017-08-23', 0.45)]

In [67]:
precip = pd.DataFrame(date_range, columns=['date', 'prcp'])
precip.set_index('date', inplace=True, )
precip.head(10)

            prcp
date
2016-08-23  0.70
2016-08-24  1.45
2016-08-25  0.11
2016-08-26  0.01
2016-08-27   NaN
2016-08-28  2.07
2016-08-29  0.90
2016-08-30  0.05
2016-08-31  2.46
2016-09-01  0.01

In [68]:
# Use Pandas to calcualte the summary statistics for the precipitation data
precip.describe()

             prcp
count  345.000000
mean     0.432087
std      0.704363
min      0.000000
25%      0.010000
50%      0.140000
75%      0.580000
max      6.700000

In [69]:
# Design a query to show how many stations are available in this dataset?
session.query(Station).count()

9

In [70]:
# What are the most active stations? (i.e. what stations have the most rows)?
# List the stations and the counts in descending order.

session.query(Measurement.station, func.count(Measurement.station)).\
    group_by(Measurement.station).\
    order_by(func.count(Measurement.station).desc()).all()

[('USC00519281', 2772),
 ('USC00519397', 2724),
 ('USC00513117', 2709),
 ('USC00519523', 2669),
 ('USC00516128', 2612),
 ('USC00514830', 2202),
 ('USC00511918', 1979),
 ('USC00517948', 1372),
 ('USC00518838', 511)]

In [71]:
# Using the station id from the previous query, calculate the lowest temperature recorded, 
# highest temperature recorded, and average temperature most active station?
session.query(func.min(Measurement.tobs), func.max(Measurement.tobs), func.avg(Measurement.tobs)).\
        filter(Measurement.station == 'USC00519281').all()

[(54.0, 85.0, 71.66378066378067)]

In [72]:
# Choose the station with the highest number of temperature observations.
# Query the last 12 months of temperature observation data for this station and plot the results as a histogram

In [73]:
sel = [Measurement.date, Measurement.tobs]
date_range = session.query(*sel).\
    filter(Measurement.date >= query_date).\
    group_by(Measurement.date).\
    order_by(Measurement.date).all()
date_range

[('2016-08-23', 74.0),
 ('2016-08-24', 74.0),
 ('2016-08-25', 77.0),
 ('2016-08-26', 80.0),
 ('2016-08-27', 74.0),
 ('2016-08-28', 71.0),
 ('2016-08-29', 78.0),
 ('2016-08-30', 75.0),
 ('2016-08-31', 76.0),
 ('2016-09-01', 77.0),
 ('2016-09-02', 75.0),
 ('2016-09-03', 75.0),
 ('2016-09-04', 73.0),
 ('2016-09-05', 76.0),
 ('2016-09-06', 73.0),
 ('2016-09-07', 74.0),
 ('2016-09-08', 74.0),
 ('2016-09-09', 75.0),
 ('2016-09-10', 75.0),
 ('2016-09-11', 71.0),
 ('2016-09-12', 72.0),
 ('2016-09-13', 75.0),
 ('2016-09-14', 73.0),
 ('2016-09-15', 73.0),
 ('2016-09-16', 73.0),
 ('2016-09-17', 76.0),
 ('2016-09-18', 75.0),
 ('2016-09-19', 70.0),
 ('2016-09-20', 70.0),
 ('2016-09-21', 73.0),
 ('2016-09-22', 73.0),
 ('2016-09-23', 73.0),
 ('2016-09-24', 77.0),
 ('2016-09-25', 76.0),
 ('2016-09-26', 74.0),
 ('2016-09-27', 74.0),
 ('2016-09-28', 77.0),
 ('2016-09-29', 77.0),
 ('2016-09-30', 73.0),
 ('2016-10-01', 74.0),
 ('2016-10-02', 73.0),
 ('2016-10-03', 76.0),
 ('2016-10-04', 74.0),
 ('2016-10-05', 75.0),
 ('2016-10-06', 75.0),
 ('2016-10-07', 73.0),
 ('2016-10-08', 74.0),
 ('2016-10-09', 77.0),
 ('2016-10-10', 74.0),
 ('2016-10-11', 74.0),
 ('2016-10-12', 78.0),
 ('2016-10-13', 75.0),
 ('2016-10-14', 73.0),
 ('2016-10-15', 74.0),
 ('2016-10-16', 77.0),
 ('2016-10-17', 70.0),
 ('2016-10-18', 74.0),
 ('2016-10-19', 70.0),
 ('2016-10-20', 73.0),
 ('2016-10-21', 74.0),
 ('2016-10-22', 75.0),
 ('2016-10-23', 72.0),
 ('2016-10-24', 71.0),
 ('2016-10-25', 74.0),
 ('2016-10-26', 75.0),
 ('2016-10-27', 71.0),
 ('2016-10-28', 68.0),
 ('2016-10-29', 71.0),
 ('2016-10-30', 76.0),
 ('2016-10-31', 69.0),
 ('2016-11-01', 73.0),
 ('2016-11-02', 76.0),
 ('2016-11-03', 74.0),
 ('2016-11-04', 74.0),
 ('2016-11-05', 69.0),
 ('2016-11-06', 77.0),
 ('2016-11-07', 71.0),
 ('2016-11-08', 71.0),
 ('2016-11-09', 71.0),
 ('2016-11-10', 71.0),
 ('2016-11-11', 67.0),
 ('2016-11-12', 73.0),
 ('2016-11-13', 72.0),
 ('2016-11-14', 74.0),
 ('2016-11-15', 72.0),
 ('2016-11-16', 72.0),
 ('2016-11-17', 75.0),
 ('2016-11-18', 75.0),
 ('2016-11-19', 73.0),
 ('2016-11-20', 74.0),
 ('2016-11-21', 71.0),
 ('2016-11-22', 73.0),
 ('2016-11-23', 69.0),
 ('2016-11-24', 69.0),
 ('2016-11-25', 69.0),
 ('2016-11-26', 70.0),
 ('2016-11-27', 69.0),
 ('2016-11-28', 71.0),
 ('2016-11-29', 67.0),
 ('2016-11-30', 72.0),
 ('2016-12-01', 71.0),
 ('2016-12-02', 71.0),
 ('2016-12-03', 67.0),
 ('2016-12-04', 76.0),
 ('2016-12-05', 67.0),
 ('2016-12-06', 67.0),
 ('2016-12-07', 68.0),
 ('2016-12-08', 71.0),
 ('2016-12-09', 68.0),
 ('2016-12-10', 68.0),
 ('2016-12-11', 69.0),
 ('2016-12-12', 65.0),
 ('2016-12-13', 70.0),
 ('2016-12-14', 69.0),
 ('2016-12-15', 64.0),
 ('2016-12-16', 60.0),
 ('2016-12-17', 70.0),
 ('2016-12-18', 67.0),
 ('2016-12-19', 72.0),
 ('2016-12-20', 73.0),
 ('2016-12-21', 70.0),
 ('2016-12-22', 68.0),
 ('2016-12-23', 69.0),
 ('2016-12-24', 69.0),
 ('2016-12-25', 69.0),
 ('2016-12-26', 71.0),
 ('2016-12-27', 71.0),
 ('2016-12-28', 71.0),
 ('2016-12-29', 69.0),
 ('2016-12-30', 65.0),
 ('2016-12-31', 65.0),
 ('2017-01-01', 68.0),
 ('2017-01-02', 70.0),
 ('2017-01-03', 71.0),
 ('2017-01-04', 70.0),
 ('2017-01-05', 71.0),
 ('2017-01-06', 65.0),
 ('2017-01-07', 70.0),
 ('2017-01-08', 66.0),
 ('2017-01-09', 69.0),
 ('2017-01-10', 64.0),
 ('2017-01-11', 66.0),
 ('2017-01-12', 68.0),
 ('2017-01-13', 67.0),
 ('2017-01-14', 70.0),
 ('2017-01-15', 68.0),
 ('2017-01-16', 68.0),
 ('2017-01-17', 69.0),
 ('2017-01-18', 73.0),
 ('2017-01-19', 71.0),
 ('2017-01-20', 67.0),
 ('2017-01-21', 67.0),
 ('2017-01-22', 68.0),
 ('2017-01-23', 70.0),
 ('2017-01-24', 67.0),
 ('2017-01-25', 69.0),
 ('2017-01-26', 67.0),
 ('2017-01-27', 69.0),
 ('2017-01-28', 64.0),
 ('2017-01-29', 67.0),
 ('2017-01-30', 66.0),
 ('2017-01-31', 65.0),
 ('2017-02-01', 65.0),
 ('2017-02-02', 60.0),
 ('2017-02-03', 60.0),
 ('2017-02-04', 66.0),
 ('2017-02-05', 69.0),
 ('2017-02-06', 73.0),
 ('2017-02-07', 68.0),
 ('2017-02-08', 68.0),
 ('2017-02-09', 64.0),
 ('2017-02-10', 70.0),
 ('2017-02-11', 66.0),
 ('2017-02-12', 65.0),
 ('2017-02-13', 68.0),
 ('2017-02-14', 79.0),
 ('2017-02-15', 71.0),
 ('2017-02-16', 72.0),
 ('2017-02-17', 70.0),
 ('2017-02-18', 72.0),
 ('2017-02-19', 68.0),
 ('2017-02-20', 69.0),
 ('2017-02-21', 65.0),
 ('2017-02-22', 69.0),
 ('2017-02-23', 72.0),
 ('2017-02-24', 68.0),
 ('2017-02-25', 66.0),
 ('2017-02-26', 64.0),
 ('2017-02-27', 69.0),
 ('2017-02-28', 69.0),
 ('2017-03-01', 64.0),
 ('2017-03-02', 72.0),
 ('2017-03-03', 78.0),
 ('2017-03-04', 70.0),
 ('2017-03-05', 68.0),
 ('2017-03-06', 76.0),
 ('2017-03-07', 72.0),
 ('2017-03-08', 68.0),
 ('2017-03-09', 72.0),
 ('2017-03-10', 65.0),
 ('2017-03-11', 82.0),
 ('2017-03-12', 69.0),
 ('2017-03-13', 69.0),
 ('2017-03-14', 75.0),
 ('2017-03-15', 76.0),
 ('2017-03-16', 77.0),
 ('2017-03-17', 68.0),
 ('2017-03-18', 70.0),
 ('2017-03-19', 74.0),
 ('2017-03-20', 74.0),
 ('2017-03-21', 72.0),
 ('2017-03-22', 72.0),
 ('2017-03-23', 70.0),
 ('2017-03-24', 70.0),
 ('2017-03-25', 72.0),
 ('2017-03-26', 72.0),
 ('2017-03-27', 74.0),
 ('2017-03-28', 69.0),
 ('2017-03-29', 69.0),
 ('2017-03-30', 73.0),
 ('2017-03-31', 76.0),
 ('2017-04-01', 69.0),
 ('2017-04-02', 71.0),
 ('2017-04-03', 73.0),
 ('2017-04-04', 75.0),
 ('2017-04-05', 69.0),
 ('2017-04-06', 72.0),
 ('2017-04-07', 74.0),
 ('2017-04-08', 76.0),
 ('2017-04-09', 70.0),
 ('2017-04-10', 72.0),
 ('2017-04-11', 71.0),
 ('2017-04-12', 70.0),
 ('2017-04-13', 73.0),
 ('2017-04-14', 72.0),
 ('2017-04-15', 70.0),
 ('2017-04-16', 71.0),
 ('2017-04-17', 69.0),
 ('2017-04-18', 71.0),
 ('2017-04-19', 71.0),
 ('2017-04-20', 69.0),
 ('2017-04-21', 70.0),
 ('2017-04-22', 73.0),
 ('2017-04-23', 70.0),
 ('2017-04-24', 75.0),
 ('2017-04-25', 74.0),
 ('2017-04-26', 77.0),
 ('2017-04-27', 76.0),
 ('2017-04-28', 71.0),
 ('2017-04-29', 68.0),
 ('2017-04-30', 58.0),
 ('2017-05-01', 73.0),
 ('2017-05-02', 79.0),
 ('2017-05-03', 70.0),
 ('2017-05-04', 74.0),
 ('2017-05-05', 74.0),
 ('2017-05-06', 74.0),
 ('2017-05-07', 70.0),
 ('2017-05-08', 66.0),
 ('2017-05-09', 72.0),
 ('2017-05-10', 72.0),
 ('2017-05-11', 78.0),
 ('2017-05-12', 70.0),
 ('2017-05-13', 71.0),
 ('2017-05-14', 70.0),
 ('2017-05-15', 72.0),
 ('2017-05-16', 71.0),
 ('2017-05-17', 71.0),
 ('2017-05-18', 69.0),
 ('2017-05-19', 68.0),
 ('2017-05-20', 70.0),
 ('2017-05-21', 69.0),
 ('2017-05-22', 72.0),
 ('2017-05-23', 69.0),
 ('2017-05-24', 70.0),
 ('2017-05-25', 75.0),
 ('2017-05-26', 72.0),
 ('2017-05-27', 72.0),
 ('2017-05-28', 73.0),
 ('2017-05-29', 74.0),
 ('2017-05-30', 72.0),
 ('2017-05-31', 75.0),
 ('2017-06-01', 74.0),
 ('2017-06-02', 76.0),
 ('2017-06-03', 74.0),
 ('2017-06-04', 77.0),
 ('2017-06-05', 74.0),
 ('2017-06-06', 74.0),
 ('2017-06-07', 79.0),
 ('2017-06-08', 75.0),
 ('2017-06-09', 72.0),
 ('2017-06-10', 72.0),
 ('2017-06-11', 76.0),
 ('2017-06-12', 74.0),
 ('2017-06-13', 73.0),
 ('2017-06-14', 74.0),
 ('2017-06-15', 77.0),
 ('2017-06-16', 74.0),
 ('2017-06-17', 72.0),
 ('2017-06-18', 77.0),
 ('2017-06-19', 76.0),
 ('2017-06-20', 74.0),
 ('2017-06-21', 75.0),
 ('2017-06-22', 76.0),
 ('2017-06-23', 71.0),
 ('2017-06-24', 73.0),
 ('2017-06-25', 79.0),
 ('2017-06-26', 79.0),
 ('2017-06-27', 74.0),
 ('2017-06-28', 74.0),
 ('2017-06-29', 76.0),
 ('2017-06-30', 75.0),
 ('2017-07-01', 74.0),
 ('2017-07-02', 78.0),
 ('2017-07-03', 77.0),
 ('2017-07-04', 77.0),
 ('2017-07-05', 75.0),
 ('2017-07-06', 74.0),
 ('2017-07-07', 74.0),
 ('2017-07-08', 71.0),
 ('2017-07-09', 78.0),
 ('2017-07-10', 77.0),
 ('2017-07-11', 74.0),
 ('2017-07-12', 72.0),
 ('2017-07-13', 77.0),
 ('2017-07-14', 76.0),
 ('2017-07-15', 78.0),
 ('2017-07-16', 75.0),
 ('2017-07-17', 72.0),
 ('2017-07-18', 77.0),
 ('2017-07-19', 74.0),
 ('2017-07-20', 75.0),
 ('2017-07-21', 72.0),
 ('2017-07-22', 72.0),
 ('2017-07-23', 78.0),
 ('2017-07-24', 77.0),
 ('2017-07-25', 79.0),
 ('2017-07-26', 73.0),
 ('2017-07-27', 75.0),
 ('2017-07-28', 73.0),
 ('2017-07-29', 77.0),
 ('2017-07-30', 79.0),
 ('2017-07-31', 74.0),
 ('2017-08-01', 72.0),
 ('2017-08-02', 80.0),
 ('2017-08-03', 76.0),
 ('2017-08-04', 77.0),
 ('2017-08-05', 77.0),
 ('2017-08-06', 79.0),
 ('2017-08-07', 78.0),
 ('2017-08-08', 74.0),
 ('2017-08-09', 71.0),
 ('2017-08-10', 75.0),
 ('2017-08-11', 72.0),
 ('2017-08-12', 74.0),
 ('2017-08-13', 80.0),
 ('2017-08-14', 79.0),
 ('2017-08-15', 70.0),
 ('2017-08-16', 71.0),
 ('2017-08-17', 72.0),
 ('2017-08-18', 76.0),
 ('2017-08-19', 71.0),
 ('2017-08-20', 78.0),
 ('2017-08-21', 76.0),
 ('2017-08-22', 76.0),
 ('2017-08-23', 76.0)]

In [74]:
temps = pd.DataFrame(date_range, columns=['date', 'tobs'])
temps.set_index('date', inplace=True, )
temps.head(10)

            tobs
date
2016-08-23  74.0
2016-08-24  74.0
2016-08-25  77.0
2016-08-26  80.0
2016-08-27  74.0
2016-08-28  71.0
2016-08-29  78.0
2016-08-30  75.0
2016-08-31  76.0
2016-09-01  77.0

![precipitation](Images/station-histogram.png)